from pathlib import Path

from snakemake.utils import validate

configfile: "config/config.yaml"

validate(config, "schemas/config.schema.yaml")

include: "rules/database_setup.smk"
include: "rules/blast.smk"

rule all:
    input:
        rules.blastn.output
    default_target: True
