from pathlib import Path

from snakemake.utils import validate

configfile: "config/config.yaml"

validate(config, "schemas/config.schema.yaml")


rule all:
  input:

include: "rules/database_setup.smk"
include: "rules/blast.smk"
