# This configuration file should be edited to fit the user's needs.

# Variables to be used across multiple rules
email: "shutchins2@umc.edu"
project: "orthology"
download_threads: 4

# Blast Database Config
database_name: "refseq_rna"
use_v5_database: True
set_blastdb: False

# Refseq Release Database Config
driver: "sqlite3"
collection_subset: "vertebrate_mammalian"
seqtype: "rna"
seqformat: "gbff"

# Blast Config
accessions_file: "test.csv"
method: 1
save_data: True
copy_from_package: False

# GenBank Config

# Alignment Config

# Phylogenetics Config